export const url = "https://fitness-server-mu.vercel.app"
// export const url = "http://11.47.163.7:8080"
export const getWorkoutScheduleUrl = url + "/get_workout_schedule_v2"
export const getWorkoutDetailsUrl = url + "/get_workout_details_v2"
export const getProgressUrl = url + "/get_progress"
export const getMealsScheduleUrl = url + "/get_meals_schedule"
export const getMealsDetailsUrl = url + "/get_meal_data/"

export const url2 = "https://fitness-server-mu.vercel.app"
// export const url2 = "http://11.47.163.7:8080"
export const testGetRecentWorkouts = url2 + "/get_recent_workouts"
export const testGetWeights= url2 + "/get_weights"
export const testGetWorkoutDay = url2 + "/get_workout_day"
export const testUpdateExercise = url2 + "/update_exercise/"
export const testAddNewExercise = url2 + "/add_new_exercise/"
