export const url = "https://fitness-server-mu.vercel.app"
// export const url = "http://10.136.142.36:8080"
export const getWorkoutScheduleUrl = url + "/get_workout_schedule"
export const getWorkoutDetailsUrl = url + "/get_workout_details"
export const getProgressUrl = url + "/get_progress"
export const getMealsScheduleUrl = url + "/get_meals_schedule"
export const getMealsDetailsUrl = url + "/get_meal_data"
export const getProfileUrl = url + "/get_profile"
export const getStreakCounterUrl = url + "/get_streak_counter"
export const getSessionProgressUrl = url + "/get_session_progress"
export const getExerciseListUrl = url + "/get_exercise_list"
export const getDailyWorkoutUrl = url + "/get_daily_workouts"
export const getExerciseGroupsUrl = url + "/get_exercise_groups"
export const getProfiles = url + "/get_profiles"

// export const url2 = "https://fitness-server-mu.vercel.app"
// export const url2 = "http://11.32.230.147:8080"
export const testGetRecentWorkouts = url + "/get_recent_workouts"
export const testGetWeights= url + "/get_weights"
export const testGetWorkoutDay = url + "/get_workout_day"
export const testUpdateExercise = url + "/update_exercise/"
export const testAddNewExercise = url + "/add_new_exercise/"
export const loginUrl = url + "/login"
export const updateSessionUrl = url + "/update_session_progress"
export const getDailyWorkoutReport = url + "/get_daily_workout_report"


export const deleteSchedWorkoutUrl = url + "/delete_sched_workout"
export const deleteDailyWorkoutUrl = url + "/delete_workout"
