// export const url = "https://fitness-server-mu.vercel.app"
export const url = "http://11.49.175.179:8080"
export const getWorkoutScheduleUrl = url + "/get_workout_schedule/profile1"
export const getWorkoutDetailsUrl = url + "/get_workout_details"
export const getProgressUrl = url + "/get_progress"
export const getMealsScheduleUrl = url + "/get_meals_schedule"
export const getMealsDetailsUrl = url + "/get_meal_data/"
export const getProfileUrl = url + "/get_profile"
export const getStreakCounterUrl = url + "/get_streak_counter"
export const getSessionProgressUrl = url + "/get_session_progress"
export const getExerciseListUrl = url + "/get_exercise_list"
export const getDailyWorkoutUrl = url + "/get_daily_workouts"

// export const url2 = "https://fitness-server-mu.vercel.app"
export const url2 = "http://11.49.175.179:8080"
export const testGetRecentWorkouts = url2 + "/get_recent_workouts"
export const testGetWeights= url2 + "/get_weights"
export const testGetWorkoutDay = url2 + "/get_workout_day"
export const testUpdateExercise = url2 + "/update_exercise/"
export const testAddNewExercise = url2 + "/add_new_exercise/"
export const loginUrl = url2 + "/login"
export const updateSessionUrl = url2 + "/update_session_progress"
export const getDailyWorkoutReport = url2 + "/get_daily_workout_report"


export const deleteSchedWorkoutUrl = url2 + "/delete_sched_workout"
export const deleteDailyWorkoutUrl = url2 + "/delete_workout"